name: release

run-name: create a release version

on:
    push:
        branches:
            - main
    workflow_dispatch: 

concurrency:
    cancel-in-progress: true
    group: "release"

jobs:
    release:
        runs-on: ubuntu-latest
        permissions: 
            contents: write
            issues: write
            pull-requests: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
      
            - name: Install node.js lts
              uses: actions/setup-node@v4
              with:
                node-version: "lts/*"

            - name: Run semantic-release  
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
              run: npx --silent semantic-release --plugins @semantic-release/commit-analyzer,@semantic-release/release-notes-generator,@semantic-release/github